// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knxemkxvsclsdagaenlg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtueGVta3h2c2Nsc2RhZ2FlbmxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDIwODUsImV4cCI6MjA3MzY3ODA4NX0.mGoxp_Zk7fU4hBflrYl0Cuu-vNCr8-sQeIIFnwWqM7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});